- .env.example
- README.md
- tests/formatString.test.ts
- tests/utils.test.ts
Fix tests imports, add disclaimer about .env on README.md
> Fix tests imports, add disclaimer about .env on README.md

- src/constants/config.ts
- src/context/StorageContractContext.tsx
- src/domain/DomainEvents.ts
- src/hooks/useMultipleEventListener.ts
- src/infrastructure/LocalStorageContractRepository.ts
- src/view/components/WalletConnectButton/AccountsSelect.tsx
- src/view/wizardView/Step3Deploy/index.tsx
Reload contracts when change Account
> Reload contracts when change Account

- src/view/wizardView/Step2Compile/generator.ts
- Add missing import to Capped and Pausable extension
- Add missing return value to  fn _before_token_transfer
> fix: add missing import and return value

- jest-environment-jsdom.js
- jest.config.js
- src/constants/config.ts
- src/constants/menu.ts
- src/data/contracts_rs/psp22_full.rs
- src/view/wizardView/Step2Compile/generator.ts
- src/view/wizardView/Step2Compile/getExtensions.ts
- tests/coreApp.test.ts
- tests/setupTests.ts
Fixing generator contracts tests
> Fixing tests

- src/view/layout/Header/MobileSection.tsx
> [Mobile] Wallet connect button

- .gitmodules
- README.md
- docker-compose.yml
- Update docker-compose to include backend and database
> feat: add backend and db to compose

- src/utils/downloadMetadata.ts
- src/view/HomeView/Table/index.tsx
Adding `downloadJson` function
> feat: add download metadata button

- src/view/wizardView/GridDeployInfo.tsx
- src/view/wizardView/Step1Extensions/Security.tsx
- src/view/wizardView/index.tsx
> Adding copy button on deploy info, changing back button title

- src/hooks/useDeployContract.ts
- src/hooks/useRecentlyClicked.ts
- src/hooks/useReportError.ts
- src/infrastructure/contractDryRun.ts
- src/utils/error.ts
- src/view/HomeView/ContractsTableWidget/ContractsTable.tsx
- src/view/wizardView/Step3Deploy/index.tsx
- yarn.lock
> Catching insufficient funds in dry running

- src/view/layout/MainDrawer/DrawerContent.tsx
> fix developed by design + wizard layout

- .github/workflows/test.yml
- package.json
- src/constants/config.ts
- src/data/contracts_rs/psp22_full.rs
- tests/coreApp.test.ts
- Fix tests and adding workflow to run test on CI #94 
- Bump version to 0.1.1
> [Hotfix] Fix tests and adding workflow to run test on CI (#94)

- .github/workflows/test.yml
- package.json
- src/constants/config.ts
- src/data/contracts_rs/psp22_full.rs
- tests/coreApp.test.ts
* Fix typo on environment variable and update contract fixed on #91 (#94)
* Fix typo on environment variable and update contract fixed on #91
* Adding workflow job to CI
* Adding environment variable
* Using config on jest
* Bump version to 0.1.1
> Upgrade Develop to 0.1.0

- jest.config.js
- package.json
- src/constants/numbers.ts
- src/context/AppNotificationContext.tsx
- src/context/NetworkAccountsContext.tsx
- src/context/StorageContractContext.tsx
- src/hooks/useCompileContract.ts
- src/hooks/useDeployContract.ts
- src/hooks/useFormInput.ts
- src/hooks/userThemeSettings.ts
- src/infrastructure/contractDryRun.ts
- src/infrastructure/deployContract.ts
- src/utils/inputValidation.ts
- src/view/wizardView/Step3Deploy/FormConstructorContract.tsx
- src/view/wizardView/Step3Deploy/index.tsx
- src/view/wizardView/Step3Deploy/initialSupplyPowDecimal.ts
- tests/sections/wizard/initialSupplyPowDecimals.test.ts
- tsconfig.paths.json
- yarn.lock
Limit number fields to uint64 used on Balance type on polkadot
> Limit number fields to uint64

- package.json
> Bump version to 0.1.3

- next.config.js
- src/view/layout/MainDrawer/DrawerContent.tsx
- src/view/layout/MainDrawer/index.tsx
- src/view/layout/MainLayout.tsx
Display version of release on footer
> Display version of release on Drawer

- .env.example
- package.json
- pages/_app.tsx
- pages/_document.tsx
- src/constants/config.ts
- yarn.lock
> Adding privacy-friendly analytics

- pages/docs/index.tsx
- src/hooks/useViewportWidth.ts
- src/view/layout/MainDrawer/DrawerContent.tsx
- src/view/wizardView/Step2Compile/index.tsx
> fix img width on mobile + Github repo link

- package.json
Update `develop` branch with `main`
> Update develop with hotfix 0.3.1

- package.json
> Update submodule commit

- src/view/components/WalletConnectButton/AccountSelect/index.tsx
> fix wallet connected indicator and disconnect icon

- src/domain/repositories/DeploymentRepository.ts
- src/infrastructure/backendApi/ApiDeploymentRepository.ts
- src/infrastructure/contractDryRun.ts
- src/view/wizardView/Step3Deploy/index.tsx
- Adding the `date` field to the deployed SmarContracts
⚠️ ~~This PR requires updates to the `/deployments` API~~.
> Adding the date field to the deployed SC

- package.json
⏫ Update `develop` branch with `main`
> Bump version 1.0.2

- package.json
⏫ Upgrade `develop` branch with `main` version.
* Update compiler-be
* Bump version 1.1.0
> Update compiler-be (#219)

- src/view/HomeView/ContractsTableWidget/ContractsTable.tsx
- src/view/HomeView/ContractsTableWidget/styled.ts
- src/view/components/NetworkBadge/index.tsx
- src/view/components/NetworkBadge/styled.ts
> Add last contracts

- src/themes/GlobalStyling.ts
- src/themes/index.tsx
- styles/globals.css
> fix layout jumping + scroll styles

- src/hooks/userContracts/useListUserContracts.ts
- src/services/localDB/UserContractsRepository.ts
- src/services/useink/walletTypes.ts
- src/view/ContractView/ContractsTable/ContractsTable.tsx
- src/view/ContractView/ContractsTable/index.tsx
- src/view/ContractView/FiltersInput.tsx
🐞[Your contracts- no contracts]  there is a text 'loading' when you filter by one value where there are not contracts https://app.clickup.com/t/86a15ttnx
🐞[Your contracts - name] Limit the quantity of character for the contracts to not to break the list https://app.clickup.com/t/86a15tt3y
🐞[Your contracts - Name] When the user deletes the contract's name, set the name in the builder (it can not be empty)
https://app.clickup.com/t/86a15tv9y
> Fix minnor bugs in contracts page table 

- src/hooks/userContracts/useListUserContracts.ts
- src/services/localDB/UserContractsRepository.ts
- src/view/ContractView/ContractsTable/index.tsx
- src/view/HomeView/ContractsTableWidget/ContractsTable.tsx
- Corrected the order of the contracts displayed in the widget
- Corrected error in the listing of contracts when it was done for the first time. (Without localstorage)
- Fix hide contracts error with the dixie indexs
> Fix minnor bugs

- src/utils/inputValidation.ts
- src/view/CustomContracts/create/CustomContractsForm.tsx
- Adding a restriction of a maximum of 20 characters in the contract name.
> Adding restriction

- src/hooks/useContractCaller.ts
- src/hooks/useContractTx.ts
- src/services/useink/utils/txUtils.ts
- src/utils/contractExecResult.ts
- src/view/ContractDetailView/ContractInteractionForm/DryRunMessage.tsx
- src/view/ContractDetailView/ContractInteractionForm/ReadMethodsForm.tsx
- src/view/ContractDetailView/ContractInteractionForm/WriteMethodsForm.tsx
- src/view/ContractDetailView/useDryRunExecution.tsx
- src/view/components/CopyButton/index.tsx
- src/view/components/MySkeleton/index.tsx
> Sign and send tx

- LICENSE
- README.md
- Change License from Apache 2.0 to GPL v3
- Add notice of use
> Update License and add notice of use

- src/constants/routes.ts
- src/view/layout/MainDrawer/DrawerContent.tsx
> Fix Github Link 

- .env.example
- .env.local.example
- README.md
- docker-compose.yml
- Fixed the share contract function in the production environment by correcting the value of the NEXT_PUBLIC_DOMAIN environment variable.
- Added a .env.local.example file to facilitate local project execution, providing a template for environment variable configuration.
> Update environment variables and README.md

- next.config.js
- package.json
- src/hooks/useContractTx.ts
- src/view/ContractDetailView/ContractInteractionForm/DryRunMessage.tsx
- src/view/ContractDetailView/ContractInteractionForm/WriteMethodsForm.tsx
- src/view/components/Accordion/styled.ts
- src/view/components/AddressAccountSelect/AccountAvatar.tsx
- src/view/components/AddressAccountSelect/index.tsx
- src/view/components/AddressAccountSelect/useStyleAutocomplete.ts
- src/view/components/BackNextButtons/index.tsx
- src/view/components/ConnectWalletSection/styled.ts
- src/view/components/DeleteContractModal/styled.tsx
- src/view/components/FactoryInputArgument/ArgAccountSelect.tsx
- src/view/components/Input/index.tsx
- src/view/components/ModalView/styled.tsx
- src/view/components/ModalWallet/styled.tsx
- src/view/components/MonoTypography/index.tsx
- src/view/components/ShareContractModal/styled.tsx
- src/view/components/StackCard/index.tsx
- src/view/components/Tabs/styled.ts
- src/view/components/WalletConnectButton/AccountSelect/styled.ts
- src/view/components/WalletConnectButton/NetworkSelect.tsx
- src/view/layout/MainDrawer/Navigation.tsx
- src/view/layout/MainLayout.tsx
- src/view/wizardView/Step1Extensions/ExtensionCheckbox.tsx
- src/view/wizardView/Step2Compile/index.tsx
- src/view/wizardView/Step3Deploy/styled.ts
- yarn.lock
- Allow introduce new Address account
> Dropdown AccountSelect

- .docker/web/dev.Dockerfile
Upgrade node version from 16 to 18 in Docker container file
> Upgrade node
